### ISSUE TITLE
Better errors if backend is misconfigured

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-link-persisted-queries#11]
If you use this link against an apollo-server backend but don't enable Engine or another PQ-supporting backend, you can end up with something like:

```
Error: Must provide document
 at invariant (/Users/glasser/Projects/Meteor/galaxy-server/node_modules/graphql/jsutils/invariant.js:18:11)
 at Object.validate (/Users/glasser/Projects/Meteor/galaxy-server/node_modules/graphql/validation/validate.js:58:34)
 at doRunQuery (/Users/glasser/Projects/Meteor/galaxy-server/node_modules/apollo-server-core/dist/runQuery.js:88:38)
```

It would be user-friendly if apollo-server-core recognized the persisted query extension enough to return the special PersistedQueryNotSupported rather than throwing with a broken invariant.

**Comment by glasser** [comment]
(Also honestly the fact that this, in a typical setup, leads to apollo-server throwing and thus reporting a 5xx error rather than a 4xx user is problematic since it is trivially caused by bad clients.)

**Comment by mxstbr** [comment]
:100: 

It'd be great if `apollo-server` detected this case and logged a warning that one has to enable Apollo Engine.

**Comment by glasser** [comment]
apollo-server 2.0 will support APQs natively.
